### ISSUE TITLE
Add support for transparency

### ISSUE THREAD

**Issue by sol** [ftorkler/x11-overlay#4]
I think it would be neat if you could specify a value for transparency (in %) on the command line.

**Comment by ftorkler** [comment]
Hi, sorry it took so long. I was on a longer summer holiday and then the day business stopped me from doing it ;)
But now I managed to implement your desired functionality and transparency (aka dimming) can be configured either via command line option or via config file. Additionally it's now possible to specify alternative default colors for fore- and background including their alpha value.
I hope this is what you were looking for and is helpful. Feedback welcome ;)
